name: Automation-exercise
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    name: 1.1.0
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Cypress tests
        uses: cypress-io/github-action@v6
